# Project: Lab Exercise 8
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Exercise_1.o Exercise_2.o
LINKOBJ  = Exercise_1.o Exercise_2.o
LIBS     = -L"D:/Data/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Data/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Data/Dev-Cpp/TDM-GCC-64/include" -I"D:/Data/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Data/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Data/Dev-Cpp/TDM-GCC-64/include" -I"D:/Data/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Data/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Data/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Lab Exercise 8.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Data\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Exercise_1.o: Exercise_1.c
	$(CC) -c Exercise_1.c -o Exercise_1.o $(CFLAGS)

Exercise_2.o: Exercise_2.c
	$(CC) -c Exercise_2.c -o Exercise_2.o $(CFLAGS)
